apiVersion: apps/v1beta1
kind: Deployment
metadata:
 name: aplicacao-deployment
spec:
 template:
  metadata:
   labels:
    name: aplicacao-deployment-pod
  spec:
   containers:
    - name: container-aplicacao
      image: tomcat
      ports:
       - containerPort: 80
